Environment: Development
Author: Mohsen
Region: us-east-1 #eu-central-1
ProjectName: ImageContentSearchLums

DeadLetterQueue:
    MaxReceiveCount: 3

Cognito:
    SelfSignUp: True
    DomainPrefix: image-content-search-lums
    AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile

Database:
    Name: images_labels_lums
    DeletionProtection: False
    Scaling:
        AutoPause: True
        Min: 2
        Max: 8
        SecondsToAutoPause: 1800

Functions:
    DefaultSignedUrlExpirySeconds: "3600"
    DefaultMaxApiCallAttempts: "5"